// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserAPIName is the fully-qualified name of the UserAPI service.
	UserAPIName = "admiral.user.v1.UserAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserAPIGetMeProcedure is the fully-qualified name of the UserAPI's GetMe RPC.
	UserAPIGetMeProcedure = "/admiral.user.v1.UserAPI/GetMe"
	// UserAPIGetUserProcedure is the fully-qualified name of the UserAPI's GetUser RPC.
	UserAPIGetUserProcedure = "/admiral.user.v1.UserAPI/GetUser"
)

// UserAPIClient is a client for the admiral.user.v1.UserAPI service.
type UserAPIClient interface {
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
}

// NewUserAPIClient constructs a client for the admiral.user.v1.UserAPI service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userAPIMethods := v1.File_user_v1_user_proto.Services().ByName("UserAPI").Methods()
	return &userAPIClient{
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+UserAPIGetMeProcedure,
			connect.WithSchema(userAPIMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+UserAPIGetUserProcedure,
			connect.WithSchema(userAPIMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userAPIClient implements UserAPIClient.
type userAPIClient struct {
	getMe   *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	getUser *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
}

// GetMe calls admiral.user.v1.UserAPI.GetMe.
func (c *userAPIClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// GetUser calls admiral.user.v1.UserAPI.GetUser.
func (c *userAPIClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// UserAPIHandler is an implementation of the admiral.user.v1.UserAPI service.
type UserAPIHandler interface {
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
}

// NewUserAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserAPIHandler(svc UserAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userAPIMethods := v1.File_user_v1_user_proto.Services().ByName("UserAPI").Methods()
	userAPIGetMeHandler := connect.NewUnaryHandler(
		UserAPIGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(userAPIMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	userAPIGetUserHandler := connect.NewUnaryHandler(
		UserAPIGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userAPIMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.user.v1.UserAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserAPIGetMeProcedure:
			userAPIGetMeHandler.ServeHTTP(w, r)
		case UserAPIGetUserProcedure:
			userAPIGetUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedUserAPIHandler struct{}

func (UnimplementedUserAPIHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.user.v1.UserAPI.GetMe is not implemented"))
}

func (UnimplementedUserAPIHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.user.v1.UserAPI.GetUser is not implemented"))
}
