// @generated by protoc-gen-connect-query v2.0.1
// @generated from file cluster/v1/cluster.proto (package admiral.cluster.v1, syntax proto3)
/* eslint-disable */

import { ClusterAPI } from "./cluster_pb";

/**
 * @generated from rpc admiral.cluster.v1.ClusterAPI.CreateCluster
 */
export const createCluster: typeof ClusterAPI["method"]["createCluster"];
/**
 * @generated from rpc admiral.cluster.v1.ClusterAPI.ListClusters
 */
export const listClusters: typeof ClusterAPI["method"]["listClusters"];
/**
 * @generated from rpc admiral.cluster.v1.ClusterAPI.GetCluster
 */
export const getCluster: typeof ClusterAPI["method"]["getCluster"];
/**
 * @generated from rpc admiral.cluster.v1.ClusterAPI.UpdateCluster
 */
export const updateCluster: typeof ClusterAPI["method"]["updateCluster"];
/**
 * @generated from rpc admiral.cluster.v1.ClusterAPI.DeleteCluster
 */
export const deleteCluster: typeof ClusterAPI["method"]["deleteCluster"];
