// @generated by protoc-gen-es v2.2.5
// @generated from file cluster/v1/cluster.proto (package admiral.cluster.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file cluster/v1/cluster.proto.
 */
export declare const file_cluster_v1_cluster: GenFile;

/**
 * @generated from message admiral.cluster.v1.Cluster
 */
export declare type Cluster = Message<"admiral.cluster.v1.Cluster"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message admiral.cluster.v1.Cluster.
 * Use `create(ClusterSchema)` to create a new message.
 */
export declare const ClusterSchema: GenMessage<Cluster>;

/**
 * @generated from message admiral.cluster.v1.CreateClusterRequest
 */
export declare type CreateClusterRequest = Message<"admiral.cluster.v1.CreateClusterRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message admiral.cluster.v1.CreateClusterRequest.
 * Use `create(CreateClusterRequestSchema)` to create a new message.
 */
export declare const CreateClusterRequestSchema: GenMessage<CreateClusterRequest>;

/**
 * @generated from message admiral.cluster.v1.CreateClusterResponse
 */
export declare type CreateClusterResponse = Message<"admiral.cluster.v1.CreateClusterResponse"> & {
  /**
   * @generated from field: admiral.cluster.v1.Cluster cluster = 1;
   */
  cluster?: Cluster;
};

/**
 * Describes the message admiral.cluster.v1.CreateClusterResponse.
 * Use `create(CreateClusterResponseSchema)` to create a new message.
 */
export declare const CreateClusterResponseSchema: GenMessage<CreateClusterResponse>;

/**
 * @generated from message admiral.cluster.v1.ListClustersRequest
 */
export declare type ListClustersRequest = Message<"admiral.cluster.v1.ListClustersRequest"> & {
  /**
   * @generated from field: string filter = 1;
   */
  filter: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: optional string page_token = 3;
   */
  pageToken?: string;
};

/**
 * Describes the message admiral.cluster.v1.ListClustersRequest.
 * Use `create(ListClustersRequestSchema)` to create a new message.
 */
export declare const ListClustersRequestSchema: GenMessage<ListClustersRequest>;

/**
 * @generated from message admiral.cluster.v1.ListClustersResponse
 */
export declare type ListClustersResponse = Message<"admiral.cluster.v1.ListClustersResponse"> & {
  /**
   * @generated from field: repeated admiral.cluster.v1.Cluster clusters = 1;
   */
  clusters: Cluster[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admiral.cluster.v1.ListClustersResponse.
 * Use `create(ListClustersResponseSchema)` to create a new message.
 */
export declare const ListClustersResponseSchema: GenMessage<ListClustersResponse>;

/**
 * @generated from message admiral.cluster.v1.GetClusterRequest
 */
export declare type GetClusterRequest = Message<"admiral.cluster.v1.GetClusterRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admiral.cluster.v1.GetClusterRequest.
 * Use `create(GetClusterRequestSchema)` to create a new message.
 */
export declare const GetClusterRequestSchema: GenMessage<GetClusterRequest>;

/**
 * @generated from message admiral.cluster.v1.GetClusterResponse
 */
export declare type GetClusterResponse = Message<"admiral.cluster.v1.GetClusterResponse"> & {
  /**
   * @generated from field: admiral.cluster.v1.Cluster cluster = 1;
   */
  cluster?: Cluster;
};

/**
 * Describes the message admiral.cluster.v1.GetClusterResponse.
 * Use `create(GetClusterResponseSchema)` to create a new message.
 */
export declare const GetClusterResponseSchema: GenMessage<GetClusterResponse>;

/**
 * @generated from message admiral.cluster.v1.UpdateClusterRequest
 */
export declare type UpdateClusterRequest = Message<"admiral.cluster.v1.UpdateClusterRequest"> & {
  /**
   * @generated from field: admiral.cluster.v1.Cluster cluster = 1;
   */
  cluster?: Cluster;
};

/**
 * Describes the message admiral.cluster.v1.UpdateClusterRequest.
 * Use `create(UpdateClusterRequestSchema)` to create a new message.
 */
export declare const UpdateClusterRequestSchema: GenMessage<UpdateClusterRequest>;

/**
 * @generated from message admiral.cluster.v1.UpdateClusterResponse
 */
export declare type UpdateClusterResponse = Message<"admiral.cluster.v1.UpdateClusterResponse"> & {
  /**
   * @generated from field: admiral.cluster.v1.Cluster cluster = 1;
   */
  cluster?: Cluster;
};

/**
 * Describes the message admiral.cluster.v1.UpdateClusterResponse.
 * Use `create(UpdateClusterResponseSchema)` to create a new message.
 */
export declare const UpdateClusterResponseSchema: GenMessage<UpdateClusterResponse>;

/**
 * @generated from message admiral.cluster.v1.DeleteClusterRequest
 */
export declare type DeleteClusterRequest = Message<"admiral.cluster.v1.DeleteClusterRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admiral.cluster.v1.DeleteClusterRequest.
 * Use `create(DeleteClusterRequestSchema)` to create a new message.
 */
export declare const DeleteClusterRequestSchema: GenMessage<DeleteClusterRequest>;

/**
 * @generated from message admiral.cluster.v1.DeleteClusterResponse
 */
export declare type DeleteClusterResponse = Message<"admiral.cluster.v1.DeleteClusterResponse"> & {
};

/**
 * Describes the message admiral.cluster.v1.DeleteClusterResponse.
 * Use `create(DeleteClusterResponseSchema)` to create a new message.
 */
export declare const DeleteClusterResponseSchema: GenMessage<DeleteClusterResponse>;

/**
 * @generated from service admiral.cluster.v1.ClusterAPI
 */
export declare const ClusterAPI: GenService<{
  /**
   * @generated from rpc admiral.cluster.v1.ClusterAPI.CreateCluster
   */
  createCluster: {
    methodKind: "unary";
    input: typeof CreateClusterRequestSchema;
    output: typeof CreateClusterResponseSchema;
  },
  /**
   * @generated from rpc admiral.cluster.v1.ClusterAPI.ListClusters
   */
  listClusters: {
    methodKind: "unary";
    input: typeof ListClustersRequestSchema;
    output: typeof ListClustersResponseSchema;
  },
  /**
   * @generated from rpc admiral.cluster.v1.ClusterAPI.GetCluster
   */
  getCluster: {
    methodKind: "unary";
    input: typeof GetClusterRequestSchema;
    output: typeof GetClusterResponseSchema;
  },
  /**
   * @generated from rpc admiral.cluster.v1.ClusterAPI.UpdateCluster
   */
  updateCluster: {
    methodKind: "unary";
    input: typeof UpdateClusterRequestSchema;
    output: typeof UpdateClusterResponseSchema;
  },
  /**
   * @generated from rpc admiral.cluster.v1.ClusterAPI.DeleteCluster
   */
  deleteCluster: {
    methodKind: "unary";
    input: typeof DeleteClusterRequestSchema;
    output: typeof DeleteClusterResponseSchema;
  },
}>;

