version: 2
project_name: admiral-server
snapshot:
  version_template: "{{ incpatch .Version }}-dev"
before:
  hooks:
    - make web
report_sizes: true
env:
  - CGO_ENABLED=0
builds:
  - id: admiral-server
    binary: admiral-server
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      pre:
        - cmd: go run cmd/assets/generate.go ./web/build
          output: true
    flags:
      - -tags=withAssets -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=admiral
checksum:
  name_template: 'checksums.txt'
sboms:
  - artifacts: archive
archives:
  - id: admiral-server
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - config.yaml
changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^feat(\([[:word:]]+\))?!?:.+$'
      order: 100
    - title: "Security Updates"
      regexp: '^sec(\([[:word:]]+\))?!?:.+$'
      order: 150
    - title: "Bug Fixes"
      regexp: '^fix(\([[:word:]]+\))?!?:.+$'
      order: 200
    - title: "Dependency Updates"
      regexp: '^(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "Documentation Updates"
      regexp: '^doc(\([[:word:]]+\))?!?:.+$'
      order: 400
    - title: "Build Process Updates"
      regexp: '^build(\([[:word:]]+\))?!?:.+$'
      order: 410
    - title: "Other Changes"
      order: 9999
release:
  footer: |
    **Full Changelog**: https://github.com/mberwanger/admiral/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out
    This release ({{ .Version }}) was built on {{ .Date }} by {{ .Env.USER }}.
    Thanks to **all** the awesome people who made it possible!
dockers:
  - image_templates:
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:v{{ .Major }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Admiral","email":"support@admiral.io"}]'
      - "--label=io.artifacthub.package.license=Apache-2.0"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - config.yaml
  - image_templates:
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-arm64"
      - "ghcr.io/mberwanger/admiral-server:v{{ .Major }}-arm64"
      - "ghcr.io/mberwanger/admiral-server:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/mberwanger/admiral-server:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Admiral","email":"support@admiral.io"}]'
      - "--label=io.artifacthub.package.license=Apache-2.0"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    extra_files:
      - config.yaml
docker_manifests:
  - name_template: "ghcr.io/mberwanger/admiral-server:{{ .Tag }}"
    image_templates:
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/mberwanger/admiral-server:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/mberwanger/admiral-server:latest"
    image_templates:
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-amd64"
      - "ghcr.io/mberwanger/admiral-server:{{ .Tag }}-arm64"

