# Go build
FROM golang:1.24-bullseye AS gobuild

WORKDIR /app

COPY ./agent ./agent
COPY ./client ./client
COPY ./tools/preflight-checks.sh ./tools/preflight-checks.sh
COPY ./Makefile .

RUN make agent

# Copy binary to final image
FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=gobuild /app/build/agent /app

CMD ["/app/agent"]