// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: authn/v1/authn.proto

package authnv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the user presents a refresh token and refresh succeeds, they will receive the token in response. Otherwise,
	// they will be redirected through the authentication flow.
	//
	// Types that are valid to be assigned to Return:
	//
	//	*LoginResponse_AuthUrl
	//	*LoginResponse_Token_
	Return        isLoginResponse_Return `protobuf_oneof:"return"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetReturn() isLoginResponse_Return {
	if x != nil {
		return x.Return
	}
	return nil
}

func (x *LoginResponse) GetAuthUrl() string {
	if x != nil {
		if x, ok := x.Return.(*LoginResponse_AuthUrl); ok {
			return x.AuthUrl
		}
	}
	return ""
}

func (x *LoginResponse) GetToken() *LoginResponse_Token {
	if x != nil {
		if x, ok := x.Return.(*LoginResponse_Token_); ok {
			return x.Token
		}
	}
	return nil
}

type isLoginResponse_Return interface {
	isLoginResponse_Return()
}

type LoginResponse_AuthUrl struct {
	AuthUrl string `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3,oneof"`
}

type LoginResponse_Token_ struct {
	Token *LoginResponse_Token `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

func (*LoginResponse_AuthUrl) isLoginResponse_Return() {}

func (*LoginResponse_Token_) isLoginResponse_Return() {}

type CallbackRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,4,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CallbackRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallbackRequest) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

type CallbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the token that the user should present. Note: this response is only valid in a gRPC context. In an HTTP
	// context the user will be redirected.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The refresh token will be empty if no refresh token was issued.
	RefreshToken  string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{3}
}

func (x *CallbackResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CallbackResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_authn_v1_authn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_authn_v1_authn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{5}
}

type LoginResponse_Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse_Token) Reset() {
	*x = LoginResponse_Token{}
	mi := &file_authn_v1_authn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Token) ProtoMessage() {}

func (x *LoginResponse_Token) ProtoReflect() protoreflect.Message {
	mi := &file_authn_v1_authn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Token.ProtoReflect.Descriptor instead.
func (*LoginResponse_Token) Descriptor() ([]byte, []int) {
	return file_authn_v1_authn_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LoginResponse_Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse_Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_authn_v1_authn_proto protoreflect.FileDescriptor

const file_authn_v1_authn_proto_rawDesc = "" +
	"\n" +
	"\x14authn/v1/authn.proto\x12\x10admiral.authn.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"1\n" +
	"\fLoginRequest\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"\xc6\x01\n" +
	"\rLoginResponse\x12\x1b\n" +
	"\bauth_url\x18\x01 \x01(\tH\x00R\aauthUrl\x12=\n" +
	"\x05token\x18\x02 \x01(\v2%.admiral.authn.v1.LoginResponse.TokenH\x00R\x05token\x1aO\n" +
	"\x05Token\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshTokenB\b\n" +
	"\x06return\"~\n" +
	"\x0fCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x04 \x01(\tR\x10errorDescription\"Z\n" +
	"\x10CallbackResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse2\xb7\x02\n" +
	"\bAuthnAPI\x12]\n" +
	"\x05Login\x12\x1e.admiral.authn.v1.LoginRequest\x1a\x1f.admiral.authn.v1.LoginResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/auth/login\x12i\n" +
	"\bCallback\x12!.admiral.authn.v1.CallbackRequest\x1a\".admiral.authn.v1.CallbackResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/auth/callback\x12a\n" +
	"\x06Logout\x12\x1f.admiral.authn.v1.LogoutRequest\x1a .admiral.authn.v1.LogoutResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/auth/logoutB\xb0\x01\n" +
	"\x14com.admiral.authn.v1B\n" +
	"AuthnProtoP\x01Z*go.admiral.io/admiral/api/authn/v1;authnv1\xa2\x02\x03AAX\xaa\x02\x10Admiral.Authn.V1\xca\x02\x10Admiral\\Authn\\V1\xe2\x02\x1cAdmiral\\Authn\\V1\\GPBMetadata\xea\x02\x12Admiral::Authn::V1b\x06proto3"

var (
	file_authn_v1_authn_proto_rawDescOnce sync.Once
	file_authn_v1_authn_proto_rawDescData []byte
)

func file_authn_v1_authn_proto_rawDescGZIP() []byte {
	file_authn_v1_authn_proto_rawDescOnce.Do(func() {
		file_authn_v1_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authn_v1_authn_proto_rawDesc), len(file_authn_v1_authn_proto_rawDesc)))
	})
	return file_authn_v1_authn_proto_rawDescData
}

var file_authn_v1_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authn_v1_authn_proto_goTypes = []any{
	(*LoginRequest)(nil),        // 0: admiral.authn.v1.LoginRequest
	(*LoginResponse)(nil),       // 1: admiral.authn.v1.LoginResponse
	(*CallbackRequest)(nil),     // 2: admiral.authn.v1.CallbackRequest
	(*CallbackResponse)(nil),    // 3: admiral.authn.v1.CallbackResponse
	(*LogoutRequest)(nil),       // 4: admiral.authn.v1.LogoutRequest
	(*LogoutResponse)(nil),      // 5: admiral.authn.v1.LogoutResponse
	(*LoginResponse_Token)(nil), // 6: admiral.authn.v1.LoginResponse.Token
}
var file_authn_v1_authn_proto_depIdxs = []int32{
	6, // 0: admiral.authn.v1.LoginResponse.token:type_name -> admiral.authn.v1.LoginResponse.Token
	0, // 1: admiral.authn.v1.AuthnAPI.Login:input_type -> admiral.authn.v1.LoginRequest
	2, // 2: admiral.authn.v1.AuthnAPI.Callback:input_type -> admiral.authn.v1.CallbackRequest
	4, // 3: admiral.authn.v1.AuthnAPI.Logout:input_type -> admiral.authn.v1.LogoutRequest
	1, // 4: admiral.authn.v1.AuthnAPI.Login:output_type -> admiral.authn.v1.LoginResponse
	3, // 5: admiral.authn.v1.AuthnAPI.Callback:output_type -> admiral.authn.v1.CallbackResponse
	5, // 6: admiral.authn.v1.AuthnAPI.Logout:output_type -> admiral.authn.v1.LogoutResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authn_v1_authn_proto_init() }
func file_authn_v1_authn_proto_init() {
	if File_authn_v1_authn_proto != nil {
		return
	}
	file_authn_v1_authn_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginResponse_AuthUrl)(nil),
		(*LoginResponse_Token_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authn_v1_authn_proto_rawDesc), len(file_authn_v1_authn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authn_v1_authn_proto_goTypes,
		DependencyIndexes: file_authn_v1_authn_proto_depIdxs,
		MessageInfos:      file_authn_v1_authn_proto_msgTypes,
	}.Build()
	File_authn_v1_authn_proto = out.File
	file_authn_v1_authn_proto_goTypes = nil
	file_authn_v1_authn_proto_depIdxs = nil
}
