// @generated by protoc-gen-connect-query v2.0.1
// @generated from file application/v1/application.proto (package admiral.application.v1, syntax proto3)
/* eslint-disable */

import { ApplicationAPI } from "./application_pb";

/**
 * @generated from rpc admiral.application.v1.ApplicationAPI.CreateApplication
 */
export const createApplication: typeof ApplicationAPI["method"]["createApplication"];
/**
 * @generated from rpc admiral.application.v1.ApplicationAPI.ListApplications
 */
export const listApplications: typeof ApplicationAPI["method"]["listApplications"];
/**
 * @generated from rpc admiral.application.v1.ApplicationAPI.GetApplication
 */
export const getApplication: typeof ApplicationAPI["method"]["getApplication"];
/**
 * @generated from rpc admiral.application.v1.ApplicationAPI.UpdateApplication
 */
export const updateApplication: typeof ApplicationAPI["method"]["updateApplication"];
/**
 * @generated from rpc admiral.application.v1.ApplicationAPI.DeleteApplication
 */
export const deleteApplication: typeof ApplicationAPI["method"]["deleteApplication"];
