// @generated by protoc-gen-es v2.2.5
// @generated from file application/v1/application.proto (package admiral.application.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file application/v1/application.proto.
 */
export declare const file_application_v1_application: GenFile;

/**
 * @generated from message admiral.application.v1.Application
 */
export declare type Application = Message<"admiral.application.v1.Application"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message admiral.application.v1.Application.
 * Use `create(ApplicationSchema)` to create a new message.
 */
export declare const ApplicationSchema: GenMessage<Application>;

/**
 * @generated from message admiral.application.v1.CreateApplicationRequest
 */
export declare type CreateApplicationRequest = Message<"admiral.application.v1.CreateApplicationRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message admiral.application.v1.CreateApplicationRequest.
 * Use `create(CreateApplicationRequestSchema)` to create a new message.
 */
export declare const CreateApplicationRequestSchema: GenMessage<CreateApplicationRequest>;

/**
 * @generated from message admiral.application.v1.CreateApplicationResponse
 */
export declare type CreateApplicationResponse = Message<"admiral.application.v1.CreateApplicationResponse"> & {
  /**
   * @generated from field: admiral.application.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message admiral.application.v1.CreateApplicationResponse.
 * Use `create(CreateApplicationResponseSchema)` to create a new message.
 */
export declare const CreateApplicationResponseSchema: GenMessage<CreateApplicationResponse>;

/**
 * @generated from message admiral.application.v1.ListApplicationsRequest
 */
export declare type ListApplicationsRequest = Message<"admiral.application.v1.ListApplicationsRequest"> & {
  /**
   * @generated from field: string filter = 1;
   */
  filter: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: optional string page_token = 3;
   */
  pageToken?: string;
};

/**
 * Describes the message admiral.application.v1.ListApplicationsRequest.
 * Use `create(ListApplicationsRequestSchema)` to create a new message.
 */
export declare const ListApplicationsRequestSchema: GenMessage<ListApplicationsRequest>;

/**
 * @generated from message admiral.application.v1.ListApplicationsResponse
 */
export declare type ListApplicationsResponse = Message<"admiral.application.v1.ListApplicationsResponse"> & {
  /**
   * @generated from field: repeated admiral.application.v1.Application applications = 1;
   */
  applications: Application[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message admiral.application.v1.ListApplicationsResponse.
 * Use `create(ListApplicationsResponseSchema)` to create a new message.
 */
export declare const ListApplicationsResponseSchema: GenMessage<ListApplicationsResponse>;

/**
 * @generated from message admiral.application.v1.GetApplicationRequest
 */
export declare type GetApplicationRequest = Message<"admiral.application.v1.GetApplicationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admiral.application.v1.GetApplicationRequest.
 * Use `create(GetApplicationRequestSchema)` to create a new message.
 */
export declare const GetApplicationRequestSchema: GenMessage<GetApplicationRequest>;

/**
 * @generated from message admiral.application.v1.GetApplicationResponse
 */
export declare type GetApplicationResponse = Message<"admiral.application.v1.GetApplicationResponse"> & {
  /**
   * @generated from field: admiral.application.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message admiral.application.v1.GetApplicationResponse.
 * Use `create(GetApplicationResponseSchema)` to create a new message.
 */
export declare const GetApplicationResponseSchema: GenMessage<GetApplicationResponse>;

/**
 * @generated from message admiral.application.v1.UpdateApplicationRequest
 */
export declare type UpdateApplicationRequest = Message<"admiral.application.v1.UpdateApplicationRequest"> & {
  /**
   * @generated from field: admiral.application.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message admiral.application.v1.UpdateApplicationRequest.
 * Use `create(UpdateApplicationRequestSchema)` to create a new message.
 */
export declare const UpdateApplicationRequestSchema: GenMessage<UpdateApplicationRequest>;

/**
 * @generated from message admiral.application.v1.UpdateApplicationResponse
 */
export declare type UpdateApplicationResponse = Message<"admiral.application.v1.UpdateApplicationResponse"> & {
  /**
   * @generated from field: admiral.application.v1.Application application = 1;
   */
  application?: Application;
};

/**
 * Describes the message admiral.application.v1.UpdateApplicationResponse.
 * Use `create(UpdateApplicationResponseSchema)` to create a new message.
 */
export declare const UpdateApplicationResponseSchema: GenMessage<UpdateApplicationResponse>;

/**
 * @generated from message admiral.application.v1.DeleteApplicationRequest
 */
export declare type DeleteApplicationRequest = Message<"admiral.application.v1.DeleteApplicationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message admiral.application.v1.DeleteApplicationRequest.
 * Use `create(DeleteApplicationRequestSchema)` to create a new message.
 */
export declare const DeleteApplicationRequestSchema: GenMessage<DeleteApplicationRequest>;

/**
 * @generated from message admiral.application.v1.DeleteApplicationResponse
 */
export declare type DeleteApplicationResponse = Message<"admiral.application.v1.DeleteApplicationResponse"> & {
};

/**
 * Describes the message admiral.application.v1.DeleteApplicationResponse.
 * Use `create(DeleteApplicationResponseSchema)` to create a new message.
 */
export declare const DeleteApplicationResponseSchema: GenMessage<DeleteApplicationResponse>;

/**
 * @generated from service admiral.application.v1.ApplicationAPI
 */
export declare const ApplicationAPI: GenService<{
  /**
   * @generated from rpc admiral.application.v1.ApplicationAPI.CreateApplication
   */
  createApplication: {
    methodKind: "unary";
    input: typeof CreateApplicationRequestSchema;
    output: typeof CreateApplicationResponseSchema;
  },
  /**
   * @generated from rpc admiral.application.v1.ApplicationAPI.ListApplications
   */
  listApplications: {
    methodKind: "unary";
    input: typeof ListApplicationsRequestSchema;
    output: typeof ListApplicationsResponseSchema;
  },
  /**
   * @generated from rpc admiral.application.v1.ApplicationAPI.GetApplication
   */
  getApplication: {
    methodKind: "unary";
    input: typeof GetApplicationRequestSchema;
    output: typeof GetApplicationResponseSchema;
  },
  /**
   * @generated from rpc admiral.application.v1.ApplicationAPI.UpdateApplication
   */
  updateApplication: {
    methodKind: "unary";
    input: typeof UpdateApplicationRequestSchema;
    output: typeof UpdateApplicationResponseSchema;
  },
  /**
   * @generated from rpc admiral.application.v1.ApplicationAPI.DeleteApplication
   */
  deleteApplication: {
    methodKind: "unary";
    input: typeof DeleteApplicationRequestSchema;
    output: typeof DeleteApplicationResponseSchema;
  },
}>;

