// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: application/v1/application.proto

package applicationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/application/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApplicationAPIName is the fully-qualified name of the ApplicationAPI service.
	ApplicationAPIName = "admiral.application.v1.ApplicationAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApplicationAPICreateApplicationProcedure is the fully-qualified name of the ApplicationAPI's
	// CreateApplication RPC.
	ApplicationAPICreateApplicationProcedure = "/admiral.application.v1.ApplicationAPI/CreateApplication"
	// ApplicationAPIListApplicationsProcedure is the fully-qualified name of the ApplicationAPI's
	// ListApplications RPC.
	ApplicationAPIListApplicationsProcedure = "/admiral.application.v1.ApplicationAPI/ListApplications"
	// ApplicationAPIGetApplicationProcedure is the fully-qualified name of the ApplicationAPI's
	// GetApplication RPC.
	ApplicationAPIGetApplicationProcedure = "/admiral.application.v1.ApplicationAPI/GetApplication"
	// ApplicationAPIUpdateApplicationProcedure is the fully-qualified name of the ApplicationAPI's
	// UpdateApplication RPC.
	ApplicationAPIUpdateApplicationProcedure = "/admiral.application.v1.ApplicationAPI/UpdateApplication"
	// ApplicationAPIDeleteApplicationProcedure is the fully-qualified name of the ApplicationAPI's
	// DeleteApplication RPC.
	ApplicationAPIDeleteApplicationProcedure = "/admiral.application.v1.ApplicationAPI/DeleteApplication"
)

// ApplicationAPIClient is a client for the admiral.application.v1.ApplicationAPI service.
type ApplicationAPIClient interface {
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error)
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error)
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error)
}

// NewApplicationAPIClient constructs a client for the admiral.application.v1.ApplicationAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApplicationAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApplicationAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	applicationAPIMethods := v1.File_application_v1_application_proto.Services().ByName("ApplicationAPI").Methods()
	return &applicationAPIClient{
		createApplication: connect.NewClient[v1.CreateApplicationRequest, v1.CreateApplicationResponse](
			httpClient,
			baseURL+ApplicationAPICreateApplicationProcedure,
			connect.WithSchema(applicationAPIMethods.ByName("CreateApplication")),
			connect.WithClientOptions(opts...),
		),
		listApplications: connect.NewClient[v1.ListApplicationsRequest, v1.ListApplicationsResponse](
			httpClient,
			baseURL+ApplicationAPIListApplicationsProcedure,
			connect.WithSchema(applicationAPIMethods.ByName("ListApplications")),
			connect.WithClientOptions(opts...),
		),
		getApplication: connect.NewClient[v1.GetApplicationRequest, v1.GetApplicationResponse](
			httpClient,
			baseURL+ApplicationAPIGetApplicationProcedure,
			connect.WithSchema(applicationAPIMethods.ByName("GetApplication")),
			connect.WithClientOptions(opts...),
		),
		updateApplication: connect.NewClient[v1.UpdateApplicationRequest, v1.UpdateApplicationResponse](
			httpClient,
			baseURL+ApplicationAPIUpdateApplicationProcedure,
			connect.WithSchema(applicationAPIMethods.ByName("UpdateApplication")),
			connect.WithClientOptions(opts...),
		),
		deleteApplication: connect.NewClient[v1.DeleteApplicationRequest, v1.DeleteApplicationResponse](
			httpClient,
			baseURL+ApplicationAPIDeleteApplicationProcedure,
			connect.WithSchema(applicationAPIMethods.ByName("DeleteApplication")),
			connect.WithClientOptions(opts...),
		),
	}
}

// applicationAPIClient implements ApplicationAPIClient.
type applicationAPIClient struct {
	createApplication *connect.Client[v1.CreateApplicationRequest, v1.CreateApplicationResponse]
	listApplications  *connect.Client[v1.ListApplicationsRequest, v1.ListApplicationsResponse]
	getApplication    *connect.Client[v1.GetApplicationRequest, v1.GetApplicationResponse]
	updateApplication *connect.Client[v1.UpdateApplicationRequest, v1.UpdateApplicationResponse]
	deleteApplication *connect.Client[v1.DeleteApplicationRequest, v1.DeleteApplicationResponse]
}

// CreateApplication calls admiral.application.v1.ApplicationAPI.CreateApplication.
func (c *applicationAPIClient) CreateApplication(ctx context.Context, req *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error) {
	return c.createApplication.CallUnary(ctx, req)
}

// ListApplications calls admiral.application.v1.ApplicationAPI.ListApplications.
func (c *applicationAPIClient) ListApplications(ctx context.Context, req *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return c.listApplications.CallUnary(ctx, req)
}

// GetApplication calls admiral.application.v1.ApplicationAPI.GetApplication.
func (c *applicationAPIClient) GetApplication(ctx context.Context, req *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return c.getApplication.CallUnary(ctx, req)
}

// UpdateApplication calls admiral.application.v1.ApplicationAPI.UpdateApplication.
func (c *applicationAPIClient) UpdateApplication(ctx context.Context, req *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error) {
	return c.updateApplication.CallUnary(ctx, req)
}

// DeleteApplication calls admiral.application.v1.ApplicationAPI.DeleteApplication.
func (c *applicationAPIClient) DeleteApplication(ctx context.Context, req *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error) {
	return c.deleteApplication.CallUnary(ctx, req)
}

// ApplicationAPIHandler is an implementation of the admiral.application.v1.ApplicationAPI service.
type ApplicationAPIHandler interface {
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error)
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error)
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error)
}

// NewApplicationAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApplicationAPIHandler(svc ApplicationAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	applicationAPIMethods := v1.File_application_v1_application_proto.Services().ByName("ApplicationAPI").Methods()
	applicationAPICreateApplicationHandler := connect.NewUnaryHandler(
		ApplicationAPICreateApplicationProcedure,
		svc.CreateApplication,
		connect.WithSchema(applicationAPIMethods.ByName("CreateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationAPIListApplicationsHandler := connect.NewUnaryHandler(
		ApplicationAPIListApplicationsProcedure,
		svc.ListApplications,
		connect.WithSchema(applicationAPIMethods.ByName("ListApplications")),
		connect.WithHandlerOptions(opts...),
	)
	applicationAPIGetApplicationHandler := connect.NewUnaryHandler(
		ApplicationAPIGetApplicationProcedure,
		svc.GetApplication,
		connect.WithSchema(applicationAPIMethods.ByName("GetApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationAPIUpdateApplicationHandler := connect.NewUnaryHandler(
		ApplicationAPIUpdateApplicationProcedure,
		svc.UpdateApplication,
		connect.WithSchema(applicationAPIMethods.ByName("UpdateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationAPIDeleteApplicationHandler := connect.NewUnaryHandler(
		ApplicationAPIDeleteApplicationProcedure,
		svc.DeleteApplication,
		connect.WithSchema(applicationAPIMethods.ByName("DeleteApplication")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.application.v1.ApplicationAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApplicationAPICreateApplicationProcedure:
			applicationAPICreateApplicationHandler.ServeHTTP(w, r)
		case ApplicationAPIListApplicationsProcedure:
			applicationAPIListApplicationsHandler.ServeHTTP(w, r)
		case ApplicationAPIGetApplicationProcedure:
			applicationAPIGetApplicationHandler.ServeHTTP(w, r)
		case ApplicationAPIUpdateApplicationProcedure:
			applicationAPIUpdateApplicationHandler.ServeHTTP(w, r)
		case ApplicationAPIDeleteApplicationProcedure:
			applicationAPIDeleteApplicationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApplicationAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedApplicationAPIHandler struct{}

func (UnimplementedApplicationAPIHandler) CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.application.v1.ApplicationAPI.CreateApplication is not implemented"))
}

func (UnimplementedApplicationAPIHandler) ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.application.v1.ApplicationAPI.ListApplications is not implemented"))
}

func (UnimplementedApplicationAPIHandler) GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.application.v1.ApplicationAPI.GetApplication is not implemented"))
}

func (UnimplementedApplicationAPIHandler) UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.application.v1.ApplicationAPI.UpdateApplication is not implemented"))
}

func (UnimplementedApplicationAPIHandler) DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.application.v1.ApplicationAPI.DeleteApplication is not implemented"))
}
