// @generated by protoc-gen-es v2.2.5
// @generated from file healthcheck/v1/healthcheck.proto (package admiral.healthcheck.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file healthcheck/v1/healthcheck.proto.
 */
export declare const file_healthcheck_v1_healthcheck: GenFile;

/**
 * @generated from message admiral.healthcheck.v1.HealthcheckRequest
 */
export declare type HealthcheckRequest = Message<"admiral.healthcheck.v1.HealthcheckRequest"> & {
};

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckRequest.
 * Use `create(HealthcheckRequestSchema)` to create a new message.
 */
export declare const HealthcheckRequestSchema: GenMessage<HealthcheckRequest>;

/**
 * @generated from message admiral.healthcheck.v1.HealthcheckResponse
 */
export declare type HealthcheckResponse = Message<"admiral.healthcheck.v1.HealthcheckResponse"> & {
};

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckResponse.
 * Use `create(HealthcheckResponseSchema)` to create a new message.
 */
export declare const HealthcheckResponseSchema: GenMessage<HealthcheckResponse>;

/**
 * @generated from service admiral.healthcheck.v1.HealthcheckAPI
 */
export declare const HealthcheckAPI: GenService<{
  /**
   * @generated from rpc admiral.healthcheck.v1.HealthcheckAPI.Healthcheck
   */
  healthcheck: {
    methodKind: "unary";
    input: typeof HealthcheckRequestSchema;
    output: typeof HealthcheckResponseSchema;
  },
}>;

