// @generated by protoc-gen-connect-query v2.0.1
// @generated from file healthcheck/v1/healthcheck.proto (package admiral.healthcheck.v1, syntax proto3)
/* eslint-disable */

import { HealthcheckAPI } from "./healthcheck_pb";

/**
 * @generated from rpc admiral.healthcheck.v1.HealthcheckAPI.Healthcheck
 */
export const healthcheck: typeof HealthcheckAPI["method"]["healthcheck"];
