// @generated by protoc-gen-es v2.2.5
// @generated from file healthcheck/v1/healthcheck.proto (package admiral.healthcheck.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file healthcheck/v1/healthcheck.proto.
 */
export const file_healthcheck_v1_healthcheck = /*@__PURE__*/
  fileDesc("CiBoZWFsdGhjaGVjay92MS9oZWFsdGhjaGVjay5wcm90bxIWYWRtaXJhbC5oZWFsdGhjaGVjay52MSIUChJIZWFsdGhjaGVja1JlcXVlc3QiFQoTSGVhbHRoY2hlY2tSZXNwb25zZTKmAQoOSGVhbHRoY2hlY2tBUEkSkwEKC0hlYWx0aGNoZWNrEiouYWRtaXJhbC5oZWFsdGhjaGVjay52MS5IZWFsdGhjaGVja1JlcXVlc3QaKy5hZG1pcmFsLmhlYWx0aGNoZWNrLnYxLkhlYWx0aGNoZWNrUmVzcG9uc2UiK4LT5JMCJVoOEgwvaGVhbHRoY2hlY2sSEy9hcGkvdjEvaGVhbHRoY2hlY2tC4AEKGmNvbS5hZG1pcmFsLmhlYWx0aGNoZWNrLnYxQhBIZWFsdGhjaGVja1Byb3RvUAFaNmdvLmFkbWlyYWwuaW8vYWRtaXJhbC9hcGkvaGVhbHRoY2hlY2svdjE7aGVhbHRoY2hlY2t2MaICA0FIWKoCFkFkbWlyYWwuSGVhbHRoY2hlY2suVjHKAhZBZG1pcmFsXEhlYWx0aGNoZWNrXFYx4gIiQWRtaXJhbFxIZWFsdGhjaGVja1xWMVxHUEJNZXRhZGF0YeoCGEFkbWlyYWw6OkhlYWx0aGNoZWNrOjpWMWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckRequest.
 * Use `create(HealthcheckRequestSchema)` to create a new message.
 */
export const HealthcheckRequestSchema = /*@__PURE__*/
  messageDesc(file_healthcheck_v1_healthcheck, 0);

/**
 * Describes the message admiral.healthcheck.v1.HealthcheckResponse.
 * Use `create(HealthcheckResponseSchema)` to create a new message.
 */
export const HealthcheckResponseSchema = /*@__PURE__*/
  messageDesc(file_healthcheck_v1_healthcheck, 1);

/**
 * @generated from service admiral.healthcheck.v1.HealthcheckAPI
 */
export const HealthcheckAPI = /*@__PURE__*/
  serviceDesc(file_healthcheck_v1_healthcheck, 0);

